### ISSUE TITLE
get null UUID error when i call QuickBlue.setNotifiable

### ISSUE THREAD

**Issue by sonamflutter** [woodemi/quick_blue#93]
(18865): Service 00001801-0000-1000-8000-00805f9b34fb
I/flutter (18865): _handleServiceDiscovery E6:6A:A1:A5:1F:D6, 00001800-0000-1000-8000-00805f9b34fb
I/flutter (18865): _handleServiceDiscovery E6:6A:A1:A5:1F:D6, 00001801-0000-1000-8000-00805f9b34fb
E/MethodChannel#quick_blue/method(18865): Failed to handle method call
E/MethodChannel#quick_blue/method(18865): java.lang.NullPointerException: Attempt to invoke virtual method 'android.bluetooth.BluetoothGattDescriptor android.bluetooth.BluetoothGattCharacteristic.getDescriptor(java.util.UUID)' on a null object reference
E/MethodChannel#quick_blue/method(18865): 	at com.example.quick_blue.QuickBluePluginKt.setNotifiable(QuickBluePlugin.kt:290)
E/MethodChannel#quick_blue/method(18865): 	at com.example.quick_blue.QuickBluePlugin.onMethodCall(QuickBluePlugin.kt:111)
E/MethodChannel#quick_blue/method(18865): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/MethodChannel#quick_blue/method(18865): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:296)
E/MethodChannel#quick_blue/method(18865): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$DartMessenger(DartMessenger.java:320)
E/MethodChannel#quick_blue/method(18865): 	at io.flutter.embedding.engine.dart.-$$Lambda$DartMessenger$TsixYUB5E6FpKhMtCSQVHKE89gQ.run(Unknown Source:12)
E/MethodChannel#quick_blue/method(18865): 	at android.os.Handler.handleCallback(Handler.java:938)
E/MethodChannel#quick_blue/method(18865): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/MethodChannel#quick_blue/method(18865): 	at android.os.Looper.loop(Looper.java:233)
E/MethodChannel#quick_blue/method(18865): 	at android.app.ActivityThread.main(ActivityThread.java:8010)
E/MethodChannel#quick_blue/method(18865): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#quick_blue/method(18865): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
E/MethodChannel#quick_blue/method(18865): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
E/flutter (18865): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(error, Attempt to invoke virtual method 'android.bluetooth.BluetoothGattDescriptor android.bluetooth.BluetoothGattCharacteristic.getDescriptor(java.util.UUID)' on a null object reference, null, java.lang.NullPointerException: Attempt to invoke virtual method 'android.bluetooth.BluetoothGattDescriptor android.bluetooth.BluetoothGattCharacteristic.getDescriptor(java.util.UUID)' on a null object reference
E/flutter (18865): 	at com.example.quick_blue.QuickBluePluginKt.setNotifiable(QuickBluePlugin.kt:290)
E/flutter (18865): 	at com.example.quick_blue.QuickBluePlugin.onMethodCall(QuickBluePlugin.kt:111)
E/flutter (18865): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/flutter (18865): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:296)
E/flutter (18865): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$DartMessenger(DartMessenger.java:320)
E/flutter (18865): 	at io.flutter.embedding.engine.dart.-$$Lambda$DartMessenger$TsixYUB5E6FpKhMtCSQVHKE89gQ.run(Unknown Source:12)
E/flutter (18865): 	at android.os.Handler.handleCallback(Handler.java:938)
E/flutter (18865): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/flutter (18865): 	at android.os.Looper.loop(Looper.java:233)
E/flutter (18865): 	at android.app.ActivityThread.main(ActivityThread.java:8010)
E/flutter (18865): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (18865): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
E/flutter (18865): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
E/flutter (18865): )
E/flutter (18865): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607:7)
E/flutter (18865): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:177:18)

**Comment by Sunbreak** [comment]
Similar to https://github.com/woodemi/quick_blue/issues/90. Could try some `Future.delayed`?
